# Generated by Django 3.2.4 on 2021-06-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
